[DEFAULT]
# Default name of requirements.txt
QIQ_REQUIREMENTS_TXT = requirements.txt

# Detect changes in QIQ_REQUIREMENTS_TXT and create qiq.json automatically
QIQ_AUTO_REQUIRE = 1

# Do you want to import pip packages?
QIQ_IMPORT_FROM_SITE_PACKAGES = 0